# permissions for end users to edit restcalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rest-operator
    app.kubernetes.io/managed-by: kustomize
  name: restcall-editor-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - restcalls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.example.com
  resources:
  - restcalls/status
  verbs:
  - get
