# permissions for end users to view restcalls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rest-operator
    app.kubernetes.io/managed-by: kustomize
  name: restcall-viewer-role
rules:
- apiGroups:
  - example.example.com
  resources:
  - restcalls
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.example.com
  resources:
  - restcalls/status
  verbs:
  - get
